name: open-llm-vtuber:cpu
services:
  vtuber:
    platform: linux/amd64
    image: open-llm-vtuber:cpu
    container_name: open-llm-vtuber-cpu

    build:
      context: ../                  
      dockerfile: dockerfiles/dockerfile.cpu
      args:
        INSTALL_BARK: "true"

    ports:
      - "12393:12393"

    volumes:
      - models_data:/app/models

    environment:
      - UV_LINK_MODE=copy

    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:12393/"]   # 若有 /health 就改成 /health
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

    restart: unless-stopped

volumes:
  models_data:
